# Part 1

In [5]:
import numpy as np

In [6]:
with open("day01.txt", "r") as file:
    data = [i.split() for i in file.read().split("\n")]

data[0:5]

[['80414', '72092'],
 ['17250', '26414'],
 ['23063', '14603'],
 ['89663', '35210'],
 ['27237', '81657']]

In [7]:
list_1 = np.array([int(i[0]) for i in data])
list_1.sort()
list_1[0:5], list_1[-5:]

(array([10078, 10154, 10202, 10412, 10448]),
 array([99783, 99816, 99819, 99853, 99883]))

In [8]:
list_2 = np.array([int(i[1]) for i in data])
list_1[0:5], list_1[-5:]

(array([10078, 10154, 10202, 10412, 10448]),
 array([99783, 99816, 99819, 99853, 99883]))

In [10]:
print(np.abs(list_1 - list_2).sum())

30311846


# Part 2

In [11]:
from collections import Counter

In [12]:
counter = Counter(list_2)

score = 0
for i in list_1:
    if i in counter.keys():
        score += i * counter[i]

print(score)

23609874
